ALTER TABLE daily_quest_generation_jobs
    ADD COLUMN IF NOT EXISTS error_code VARCHAR(80),
    ADD COLUMN IF NOT EXISTS target_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS existing_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS duration_ms BIGINT NOT NULL DEFAULT 0;
